services:
  godotxt:
    build: .
    container_name: godotxt
    restart: unless-stopped
    user: "1000:1000" # User and group 1000 for proper permission for volumes
    ports:
      - "8080:3000" # Change the first port to your preferred EX: "5050:3000"
    env_file: # Optional if using authentication token
      - .env
    volumes:
      - ./data:/app/data # Change to your own folder
